### PR TITLE
options for several methods

### PR DESCRIPTION
**Pull request by ravlio**
Allow passing a message when:

promoting  / demoting moderators

ban / unban a user (API call only, not for /ban /unban commands)

invite user

accept invite

reject invite

### CODE REVIEW

**Comment by ravlio** [comment]
@Bogdan-D @pascaldekloe I did not miss a point, please consider my variant more like a proposal. Let's discuss it. Do we really need to copy methods just to provide "optional" options / because Go has no method overloading? There are some straightforward solutions, from rpc-like to Options pattern https://github.com/tmrts/go-patterns/blob/master/idiom/functional-options.md

What do you think?

**Comment by tbarbugli** [comment]
@ravlio I think all other API clients accept a message parameter, not an option parameter; I also think we should not create an option type for only 1 option. I rather break the library the day we actually need more than just an optional message.

**Comment by ravlio** [comment]
@tbarbugli I'm confused. What to choose? The optional message (as a pointer) was initially. Rolling back to it?

**Comment by Bogdan-D** [comment]
my point is that having methods witch requires to pass `nil` all the time is ugly. I haven't idea how to avoid it best when I've started work on `stream-chat-go`, but now I have clear picture.

@tbarbugli you also told the same in past review, now your point of view is changed?

**Comment by Bogdan-D** [comment]
I like this way the best from easy to use:
https://play.golang.org/p/455sVvyCjVU

the only problem `godoc` has bad support for this yet, to show which options can be passed to function

**Comment by ravlio** [comment]
now should be better @tbarbugli @Bogdan-D

**Pull request merged**
