### PR TITLE
ci: bump go.mod file

### PR DESCRIPTION
**Pull request by peterdeme**
Bump go.mod file with major version

### CODE REVIEW

**Comment by ferhatelmas** [comment]
looks good but how about https://github.com/GetStream/stream-chat-go#installation

**Comment by peterdeme** [comment]
@ferhatelmas uhh, didn't know about it. adding in a min

**Comment by yaziine** [comment]
@peterdeme can we move the `.versionrc.js` file into `scripts` folder?

**Review by yaziine — APPROVED** [review]
LGTM

**Pull request merged**
