### PR TITLE
ci: add release flow

### PR DESCRIPTION
**Pull request by peterdeme**
Here's how an example looks like: https://github.com/GetStream/stream-chat-net/pull/89

### CODE REVIEW

**Comment by yaziine** [comment]
Is it possible to have the changelog directly in the description? We could use something like this: https://github.com/mikepenz/release-changelog-builder-action

**Comment by peterdeme** [comment]
@yaziine it's automatic: https://github.com/GetStream/stream-chat-go/pull/167/files#diff-b93b84f6a7bc16fd654fc88ad84bd92fa34871e6f1b36926523efa7a5fa60ae3R22

The only caveat is that you need to follow [conventional commits](https://www.conventionalcommits.org/) for your commit messages.

**Review by ferhatelmas — APPROVED** [review]
LGTM

**Comment by ferhatelmas** [comment]
updated actions and could you modify owners? maybe replace me with Amin

**Comment by yaziine** [comment]
>it's automatic: https://github.com/GetStream/stream-chat-go/pull/167/files#diff-b93b84f6a7bc16fd654fc88ad84bd92fa34871e6f1b36926523efa7a5fa60ae3R22

By manually, I meant the script `get_changelog_diff.js`

**Review by yaziine — APPROVED** [review]

**Review by ferhatelmas — APPROVED** [review]

**Comment by ferhatelmas** [comment]
> > it's automatic: #167 (files)

> By manually, I meant the script get_changelog_diff.js

if we can get rid of it, definitely better but good for now.

**Pull request merged**
